management:
  endpoints:
    web:
      cors:
        allowed-origins: '*'
        allowed-methods: '*'
        allowed-headers: '*'
spring:
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        healthCheckPath: /management/health
        healthCheckInterval: 15s
  data:
    mongodb:
      database: ${MONGO_DATABASE:drscans}
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
