server:
  port: 8180
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["health"]
  endpoint:
    health:
      show-details: when_authorized
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration
# ===================================================================
application:
  queue:
    name: 'idscan-queue'
  securitech:
    url:
      callback: 'net.tcp://twinxsdrc.securiportal.com:16000/DRProxyINTCbC'
      soap: 'http://broker.accoda.nl:8080/DRProxySOAP'
      rest: 'http://broker.accoda.nl:8080/DRProxyREST'
    retention:
      cron: ${SCANSERVICE_RETENTION_CRON:* * * * * *}
      days: ${SCANSERVICE_RETENTION_DAYS:3}
    token: '2d382644-bb54-4130-928b-cddb2c69e070'
